spring.application.name=alarm-notification
server.port=8080

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hwangcw@devfox.co.jp
spring.mail.password=crgf hrsx qjix lcmq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true